services:
- type: web
  name: hostmi
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
#  pullRequestPreviewEnabled: true
  
  envVars:
  - key: NODE_ENV
    value: production
